// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using K23CNT3_VuTienDuc_2310900023.Models;

#nullable disable

namespace VtdBuoi07Lab08.Migrations
{
    [DbContext(typeof(VtdAppDbContext))]
    [Migration("20260802021631_Vtdv1")]
    partial class Vtdv1
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.29")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("VtdBuoi07Lab08.Models.VtdAccount", b =>
                {
                    b.Property<int>("VtdId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("VtdId"));

                    b.Property<string>("VtdAvatar")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VtdEmail")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VtdName")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("VtdPassword")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("VtdId");

                    b.ToTable("VtdAccount");
                });

            modelBuilder.Entity("VtdBuoi07Lab08.Models.VtdBanner", b =>
                {
                    b.Property<int>("VtdId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("VtdId"));

                    b.Property<DateTime>("VtdCreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("VtdDescription")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VtdImage")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VtdName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("VtdPrioty")
                        .HasColumnType("int");

                    b.Property<byte>("VtdStatus")
                        .HasColumnType("tinyint");

                    b.HasKey("VtdId");

                    b.ToTable("VtdBanner");
                });

            modelBuilder.Entity("VtdBuoi07Lab08.Models.VtdBlog", b =>
                {
                    b.Property<int>("VtdId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("VtdId"));

                    b.Property<DateTime>("VtdCreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("VtdDescription")
                        .IsRequired()
                        .HasMaxLength(1500)
                        .HasColumnType("nvarchar(1500)");

                    b.Property<string>("VtdImage")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VtdName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<byte>("VtdStatus")
                        .HasColumnType("tinyint");

                    b.Property<int>("VtdViewCount")
                        .HasColumnType("int");

                    b.HasKey("VtdId");

                    b.ToTable("VtdBlog");
                });

            modelBuilder.Entity("VtdBuoi07Lab08.Models.VtdCategory", b =>
                {
                    b.Property<int>("VtdId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("VtdId"));

                    b.Property<DateTime>("VtdCreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("VtdDescription")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VtdImage")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VtdName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<byte>("VtdStatus")
                        .HasColumnType("tinyint");

                    b.HasKey("VtdId");

                    b.HasIndex("VtdName")
                        .IsUnique();

                    b.ToTable("VtdCategory");
                });

            modelBuilder.Entity("VtdBuoi07Lab08.Models.VtdCustomer", b =>
                {
                    b.Property<int>("VtdId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("VtdId"));

                    b.Property<string>("VtdAddress")
                        .IsRequired()
                        .HasMaxLength(35)
                        .HasColumnType("nvarchar(35)");

                    b.Property<string>("VtdAvatar")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("VtdBirthday")
                        .HasColumnType("datetime2");

                    b.Property<string>("VtdEmail")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VtdFacebook")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VtdFullName")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("VtdGender")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VtdPassword")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VtdPhone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("VtdId");

                    b.ToTable("VtdCustomer");
                });

            modelBuilder.Entity("VtdBuoi07Lab08.Models.VtdOrderDetail", b =>
                {
                    b.Property<int>("VtdId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("VtdId"));

                    b.Property<int>("VtdOrderId")
                        .HasColumnType("int");

                    b.Property<float>("VtdPrice")
                        .HasColumnType("real");

                    b.Property<int>("VtdProductId")
                        .HasColumnType("int");

                    b.Property<int>("VtdQuantity")
                        .HasColumnType("int");

                    b.HasKey("VtdId");

                    b.HasIndex("VtdProductId");

                    b.HasIndex("VtdOrderId", "VtdProductId")
                        .IsUnique();

                    b.ToTable("VtdOrderDetail");
                });

            modelBuilder.Entity("VtdBuoi07Lab08.Models.VtdOrders", b =>
                {
                    b.Property<int>("VtdId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("VtdId"));

                    b.Property<string>("VtdAddress")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("VtdCreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("VtdCustomerId")
                        .HasColumnType("int");

                    b.Property<string>("VtdEmail")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VtdName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte>("VtdStatus")
                        .HasColumnType("tinyint");

                    b.HasKey("VtdId");

                    b.HasIndex("VtdCustomerId");

                    b.ToTable("VtdOrders");
                });

            modelBuilder.Entity("VtdBuoi07Lab08.Models.VtdProduct", b =>
                {
                    b.Property<int>("VtdId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("VtdId"));

                    b.Property<int>("VtdCategoryId")
                        .HasColumnType("int");

                    b.Property<DateTime>("VtdCreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("VtdDescription")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("VtdImage")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VtdName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<float>("VtdPrice")
                        .HasColumnType("real");

                    b.Property<float>("VtdSalePrice")
                        .HasColumnType("real");

                    b.Property<byte>("VtdStatus")
                        .HasColumnType("tinyint");

                    b.HasKey("VtdId");

                    b.HasIndex("VtdCategoryId");

                    b.ToTable("VtdProduct");
                });

            modelBuilder.Entity("VtdBuoi07Lab08.Models.VtdOrderDetail", b =>
                {
                    b.HasOne("VtdBuoi07Lab08.Models.VtdOrders", "VtdOrder")
                        .WithMany()
                        .HasForeignKey("VtdOrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("VtdBuoi07Lab08.Models.VtdProduct", "VtdProduct")
                        .WithMany()
                        .HasForeignKey("VtdProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("VtdOrder");

                    b.Navigation("VtdProduct");
                });

            modelBuilder.Entity("VtdBuoi07Lab08.Models.VtdOrders", b =>
                {
                    b.HasOne("VtdBuoi07Lab08.Models.VtdCustomer", "VtdCustomer")
                        .WithMany()
                        .HasForeignKey("VtdCustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("VtdCustomer");
                });

            modelBuilder.Entity("VtdBuoi07Lab08.Models.VtdProduct", b =>
                {
                    b.HasOne("VtdBuoi07Lab08.Models.VtdCategory", "VtdCategory")
                        .WithMany("VtdProducts")
                        .HasForeignKey("VtdCategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("VtdCategory");
                });

            modelBuilder.Entity("VtdBuoi07Lab08.Models.VtdCategory", b =>
                {
                    b.Navigation("VtdProducts");
                });
#pragma warning restore 612, 618
        }
    }
}
